version: "3.9"
services:
  web:
    build: ./web
    ports:
      - ${PORT:-5000}:5000
    command:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: '1'
      FLASK_APP: app